### PR TITLE
NODERS Team validator

### PR DESCRIPTION
**Pull request by nodersteam**
Tell me what node you set, and I will tell you who you are

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by nodersteam** [comment]
@nullmames done

**Comment by nullmames** [comment]
hi @nodersteam you have not resynced the fork. please make sure you have the right branch selected and clyc the sync button near the top.

**Comment by nodersteam** [comment]
image
@nullmames already done

**Pull request merged**
