### PR TITLE
Create kokorin9-gentx.json

### PR DESCRIPTION
**Pull request by Kokorin9**

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by Kokorin9** [comment]
> please resync your fork

Done

**Comment by nullmames** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by Kokorin9** [comment]
Done, resynced again

**Comment by nullmames** [comment]
Please follow the instructiond and be sure you have the `patch-2` branch of your fork selected before you resync.

**Comment by Kokorin9** [comment]
Did synch, did update the branch

**Comment by nullmames** [comment]
You need to click resync from the page in the link below. If not done in the next 2 hours i will close this PR.
https://github.com/Kokorin9/testnet-1/tree/patch-2

**Comment by nullmames** [comment]
No response. Closing.

**Pull request closed without merging**
