### PR TITLE
create gentx flnn

### PR DESCRIPTION
**Pull request by flnnhuman**

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by flnnhuman** [comment]
done

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by flnnhuman** [comment]
done, please, run your tests again

**Comment by nullmames** [comment]
Gentx fails checks

**Pull request closed without merging**
