### PR TITLE
Noderunners gentx

### PR DESCRIPTION
**Pull request by rewseRE**

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by rewseRE** [comment]
Resync done.

**Comment by nullmames** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by rewseRE** [comment]
It's done. What to do next? Close and resubmit PR? Create a new PR?

**Comment by rewseRE** [comment]
@nullmames 
I think the problem is that I was creating a new file in your repository and not in my own fork. If I close and reopen this PR, it will lost the number #254.

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

**Comment by nullmames** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by rewseRE** [comment]
@nullmames 
Done.
defund

**Comment by nullmames** [comment]
Please make sure you have your branch `patch-3` of your fork selected when you resync

**Pull request merged**
