### PR TITLE
Add Seasting gentx

### PR DESCRIPTION
**Pull request by BadaBing01**

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by BadaBing01** [comment]
> please resync your fork

resynced

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by BadaBing01** [comment]
> sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

hey, resynced. no problems)

**Pull request merged**
