### PR TITLE
Create gentx-Kalia-Network.json

### PR DESCRIPTION
**Pull request by KaliaNetwork**

### CODE REVIEW

**Review by KaliaNetwork — COMMENTED** [review]
test - review request

**Review by KaliaNetwork — COMMENTED** [review]
test request

**Comment by KaliaNetwork** [comment]
need to approval to check again @nullmames

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by KaliaNetwork** [comment]
sycned @nullmames

**Comment by nullmames** [comment]
your gentx file is no good. Ill have to close this PR.

**Comment by KaliaNetwork** [comment]
@nullmames could you check your Discord dm  from this handle sr#3753

**Pull request closed without merging**
