### PR TITLE
Create gentx-kallen.json

### PR DESCRIPTION
**Pull request by Kallen-c**

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by Kallen-c** [comment]
> 

done

**Comment by nullmames** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by Kallen-c** [comment]
> Reference

done

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by Kallen-c** [comment]
thanks

**Comment by Kallen-c** [comment]
done

**Pull request merged**
