### PR TITLE
gentx-Murzilka.json

### PR DESCRIPTION
**Pull request by EcaterinaSm**

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by EcaterinaSm** [comment]
> please resync your fork

Done.

**Comment by nullmames** [comment]
sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by EcaterinaSm** [comment]
> sorry to do this, can you please resync again so i can run the updated script now that the time in the script has expired.
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

No problem. I did the resync again.
Merge my PR please.

**Pull request merged**
