### PR TITLE
Merge branch 'defund-labs:main' into main

### PR DESCRIPTION
**Pull request by 88Mikhail88**
Create gentx-Home_Validator

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by 88Mikhail88** [comment]
Merge branch 'defund-labs:main' into main

**Comment by 88Mikhail88** [comment]
done

**Review by 88Mikhail88 — COMMENTED** [review]
Merge branch 'defund-labs:main' into main

**Comment by 88Mikhail88** [comment]
check

**Comment by nullmames** [comment]
not sure what you have done mate. you are 115 commits behind

**Comment by 88Mikhail88** [comment]
I'm not sure what that means: "resync your fork"

**Comment by 88Mikhail88** [comment]
maybe so )

**Comment by nullmames** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by nullmames** [comment]
you also need to revert this commit
https://github.com/defund-labs/testnet/pull/244/commits/27d3b20717260da10c5d0970e892d0ac0e20662e

**Comment by 88Mikhail88** [comment]
Thanks, I'm reading.

**Comment by 88Mikhail88** [comment]
Thank you! "A Century of Living, A Century of Learning"

**Comment by nullmames** [comment]
You have two gentx files on the PR. you need to delete the one outside the gentx folder

**Comment by 88Mikhail88** [comment]
delete

**Comment by 88Mikhail88** [comment]
Thank you for your help and your time!

**Pull request merged**
