### PR TITLE
gentx by node ADDICT

### PR DESCRIPTION
**Pull request by iADDICTi**
gentx by node ADDICT

### CODE REVIEW

**Comment by nullmames** [comment]
please resync your fork

**Comment by iADDICTi** [comment]
done

**Review by iADDICTi — COMMENTED** [review]
sorry missclick, i closed pr, can u back me?

**Comment by nullmames** [comment]
I cant reopen your PR, i think you can but.

FYI you are currently outside the cutoff which is PR #315 

I will be going up the list if there are CI failures.

**Comment by iADDICTi** [comment]
done

**Comment by nullmames** [comment]
Please remove the gentx that is outside the testnet folder

**Comment by iADDICTi** [comment]
done

**Pull request closed without merging**
