### PR TITLE
Gentx

### PR DESCRIPTION
**Pull request by olegufa6565**

### CODE REVIEW

**Comment by olegufa6565** [comment]
Gavryushev gentx

**Comment by nullmames** [comment]
please resync your fork

**Comment by olegufa6565** [comment]
Done. What should I do next?

**Comment by olegufa6565** [comment]
Please transfer the file from testnet/defund-private-2/ to the /gentx folder... I made a mistake and put it in the wrong folder.

  
>Пятница, 28 октября 2022, 11:16 +05:00 от nullmames ***@***.***>:
> 
> 
>Merged  #293 into main.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <defund-labs/testnet/pull/293/issue_event/7688456003 @ github . com> 
 
 
--
Гаврюшев Олег
Отправлено из Почты  Mail.ru

**Pull request merged**
